version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./DatabaseScripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"